### ISSUE TITLE
Object related error

### ISSUE THREAD

**Issue by RakhimyanTim** [duytq94/flutter-chat-demo#1]
Hi! I've tried to use your case but received some object related error. Please give me some explanation. Thnks!
![image](https://user-images.githubusercontent.com/13000093/44630476-c10f2e00-a977-11e8-890e-8d2a2aae58e6.png)

![image](https://user-images.githubusercontent.com/13000093/44630439-31697f80-a977-11e8-8693-d97d004dfc09.png)

**Comment by duytq94** [comment]
Hi @RakhimyanTim ,
It's just the warning, don't worry about it. Everything still works fine.
https://github.com/flutter/flutter/issues/18663

**Comment by RakhimyanTim** [comment]
@duytq94 Thanks
