### ISSUE TITLE
Image is not uploading

### ISSUE THREAD

**Issue by amizanali** [duytq94/flutter-chat-demo#10]
I'm having an error when trying to upload an image file, this is from iOS simulator. 

"This file is not an image"

this is the Rules setup on Storage for firebase

service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read: if true;
      allow write: if true && request.resource.contentType.matches('image/.*');
    }
  }
}

**Comment by duytq94** [comment]
Hi @amizanali 
Thanks for your report, you're right. iOS always not match the condition even you upload the image.
Currently, I haven't found the best solution to this issue.
Maybe you remove the condition on firebase rule.
Or change the condition to check if the file match *.jpg || *.png (not catch all case) (more at here https://firebase.google.com/docs/reference/security/storage/#resource_1)
Or check the file in the client before uploading to the server.

**Comment by duytq94** [comment]
You can see here, iOS has the type is application/octet-stream
![screen shot 2019-02-13 at 10 43 59 pm](https://user-images.githubusercontent.com/24253421/52723916-f8829d00-2fe0-11e9-86f6-9652ec0f9d0a.png)
