### ISSUE TITLE
How send a notification to other user before proceed the chat.

### ISSUE THREAD

**Issue by pyclasses** [duytq94/flutter-chat-demo#12]
What i want as a feature in your app.
Suppose we have 5 users.
1) Elon
2) Bill
3) Jeff
4) Tony
5) Richie(me)

When i open the app, all users are show.
When i tap on some user(suppose Elon), the chat activity appears.
But instead of direct access of the chat activity, first we have to send a notification to the user(Elon), if he accepts our invitation then the chat activity appears.

**Comment by duytq94** [comment]
Hi, this demo just makes the simplest chat app so I didn't do this feature. But you can try this way.
First, you need to create a collection name statusFriend, and it contains a status between two users (0 = sent request, 1 = accepted, 2 = canceled...). Every time you start a chat session, you just check this status and show appropriate UI to the current user. Push features can be implemented by Firebase Cloud Messaging and be triggered by Firebase Function.
Keep feeling free to discuss.
Thanks.

**Comment by pyclasses** [comment]
Thanks @duytq94 for your suggestion. 

I am new in flutter and also firebase, I don't know how to build.

It's a humble request, Please help me.
