### ISSUE TITLE
App doesn't work

### ISSUE THREAD

**Issue by AngelGordillo** [duytq94/flutter-chat-demo#13]
Hi sir,
I imagine that definitely, I'm doing something wrong. I've followed all your steps and I get this error every time 
![image](https://user-images.githubusercontent.com/30040940/57923960-f95af180-78a3-11e9-9080-c320448e7a8a.png)
Can you help me? 
Thanks

**Comment by duytq94** [comment]
Hi @AngelGordillo ,
Do you make sure all your plugins have the same version like my pubspec.yaml?
Also check out here:
https://github.com/flutter/flutter/issues/17951
https://github.com/flutter/flutter/issues/17457
