### ISSUE TITLE
Text overflow

### ISSUE THREAD

**Issue by FilipeOS** [duytq94/flutter-chat-demo#14]
Hi,

How can we make the Text Container adapt to the height of a long text? Right now it crops and I can't find anything on web that resolves properly.

Please advise.

**Comment by duytq94** [comment]
Where text is cropped, can you give me a screenshot?
I tested and message text is fine.

![Screenshot_20190521-174934](https://user-images.githubusercontent.com/24253421/58090219-f4be7200-7bf0-11e9-9d48-a8addf5aa2aa.jpg)

**Comment by FilipeOS** [comment]
I've fixed already using a Flexible, thank you
