### ISSUE TITLE
does not load further page after pressing "Sign in with google"

### ISSUE THREAD

**Issue by Aakash-DD** [duytq94/flutter-chat-demo#18]
does not load further page after pressing "Sign in with google".
onPressed "Sign in with google does not work out and thus does not move to next page.....?

**Comment by duytq94** [comment]
Did you install exactly version packages I mentioned in the article?
Which channel you are using? Some channel like master has some issues with sending the message in Firestore.
Btw, giving some logs is better than just a shorting describe so we can find out the issues.

**Comment by Aakash-DD** [comment]
Step 1:
![Screenshot_20190628_163724](https://user-images.githubusercontent.com/33255535/60338356-55488800-99c3-11e9-99b8-92c63613c7ea.jpg)


Step 2:

![Screenshot_20190628_163741](https://user-images.githubusercontent.com/33255535/60338382-68f3ee80-99c3-11e9-96b7-4ac272d5432f.jpg)


after this, stuck on the loading screen (step 2)....for half and hour...... :(

**Comment by Aakash-DD** [comment]
Also tell me, i created only :
1) chat.dart
2) settings.dart
3)login.dart
4)const.dart
5)main.dart


and started working...till then it does not allow me to signUp / Sigin.

BTW.all packages are well setup. 
Or is there any other thing to be done.....(except stickers)...from my side?

**Comment by Aakash-DD** [comment]
@duytq94 got any solution sir?

**Comment by duytq94** [comment]
You should check the logcat, I think IDE will notify you something about the errors, maybe something wrong at the config firebase auth.

**Comment by polpokpol** [comment]
did you use:
`final FirebaseUser user = await _auth.signInWithGoogle();` in your code ? 

because google changed the api, using ".signInWithGoogle" will not work especially to the newer versions of flutter.

if so reply to this issue maybe i can help.

**Comment by Aakash-DD** [comment]
@polpokpol  no,it's not there.
I know it is changed with signin with credentials

**Comment by Aakash-DD** [comment]
@polpokpol if you have setup this...may be please can you make a screen recording video for this.
How to setup and run this.
Please Bro !!

**Comment by polpokpol** [comment]
im on my phone right now so I cant take a video or picture. From what i remember is i have solved this by going to my firebase console authentication, and click the sign in method, enable the google sign in and lastly put your email in the project support email.
![Selection_024](https://user-images.githubusercontent.com/40071594/60362811-708fb380-9a14-11e9-8093-0e70943961d5.png)
this is only a screenshot from the internet.

**Comment by FilipeOS** [comment]
I would recommend to execute the app, clean log, try to login and after that paste the log (since will get stuck, some issue happened).

**Comment by Aakash-DD** [comment]
Okh, done.Sign in was success,
but this error comes up:

![Screenshot_20190629_222139](https://user-images.githubusercontent.com/33255535/60387373-91611300-9abf-11e9-8ec7-6363cfdc84a8.jpg)

And also this is not updating + white blank screen comes up when sign in was success.
Thanks

**Comment by Aakash-DD** [comment]
@duytq94  any suggestion? sir

**Comment by duytq94** [comment]
I think the error message is quite clear that your path (projects/signin-66177/databases/(default)/documents.users/...) is wrong so you can't update the data.

**Comment by duytq94** [comment]
I think the error message is quite clear that your path (projects/signin-66177/databases/(default)/documents/users/...) is wrong so you can't update the data.

**Comment by duytq94** [comment]
About "white blank screen comes up when sign in was success" maybe cause by 2 reasons:

- Your db only has one user, please add more some users so they can see each other.

- Your path to getting list user is wrong so don't have any user to render the list

**Comment by duytq94** [comment]
This issue should be close since it does not happen on the main project.
Thanks all.
