### ISSUE TITLE
Allow group chats

### ISSUE THREAD

**Issue by FilipeOS** [duytq94/flutter-chat-demo#19]
Hi @duytq94 

How hard it would be to start allowing group chats? Can you advise?

**Comment by duytq94** [comment]
I think group chat can be deployed without too much effort.

- First let the user create a group (should add a collection named `groups` next `users` and `messages` have already existed) with the group name, users invited (we had list users for choosing)...

- Second, if a user is invited, update a field named `my_group` in that user node (to getting all group the current user be invited later).

- Then design another screen to load all group chat the current user joined, if the user goes to any group, get this group's details then render the UI.

**Comment by FilipeOS** [comment]
@duytq94 to simplify I can create manually group chats /rooms and people only join and text right? I guess your code already do that?

Or I would need to change something?

Sorry so many questions, I'm still very noob
