### ISSUE TITLE
App is not running

### ISSUE THREAD

**Issue by davigun** [duytq94/flutter-chat-demo#2]
Why cant i run the project ?

E/flutter ( 7521): [ERROR:flutter/shell/common/engine.cc(149)] Could not prepare to run the isolate.
E/flutter ( 7521): [ERROR:flutter/shell/common/engine.cc(114)] Engine not prepare and launch isolate.
E/flutter ( 7521): [ERROR:flutter/shell/platform/android/android_shell_holder.cc(136)] Could not launch engine in configuration.

the error message

**Comment by davigun** [comment]
E/flutter ( 7521): [ERROR:flutter/shell/common/engine.cc(149)] Could not prepare to run the isolate.
E/flutter ( 7521): [ERROR:flutter/shell/common/engine.cc(114)] Engine not prepare and launch isolate.
E/flutter ( 7521): [ERROR:flutter/shell/platform/android/android_shell_holder.cc(136)] Could not launch engine in configuration.

**Comment by davigun** [comment]
Hello mate, can you help me out

**Comment by davigun** [comment]
i need to know in what flutter version are you developing? cause mine is in 0.7.3

**Comment by davigun** [comment]
Please help me out, i need this to be working

**Comment by duytq94** [comment]
Hi @davigun , sorry for late, I don't usually check issues.
Do you do every step in this guide:
https://medium.com/flutter-community/building-a-chat-app-with-flutter-and-firebase-from-scratch-9eaa7f41782e

**Comment by duytq94** [comment]
Hi @davigun , I just clone and run again, seem everything fine.
Did you run "flutter packages get" and make sure do this config
![image](https://user-images.githubusercontent.com/24253421/45624291-2b694900-bab4-11e8-83b0-6ffaf7e0fa60.png)

**Comment by duytq94** [comment]
If it still happens, let run `flutter upgrade` for trying

**Comment by davigun** [comment]
@duytq94 did you use Android studio for dev? i'am using VS code. Do i have to set up my own firebase to use this? or can i use ur default to run test the app?

**Comment by duytq94** [comment]
Hi @davigun 
I detected the issue, by default flutter will find `void main() => runApp(new MyApp());` at `main.dart`, but in my case, I set it up at `login.dart` and in Android Studio, you can set which file will start first, but it can't in VS Code.
So the fastest solution is move `void main() => runApp(new MyApp());` at `login.dart` to `main.dart` then it will work fine.

![image](https://user-images.githubusercontent.com/24253421/45627558-6bccc500-babc-11e8-9fd0-a0bb44f305eb.png)

**Comment by duytq94** [comment]
Work fine in VS Code then

![image](https://user-images.githubusercontent.com/24253421/45627649-9dde2700-babc-11e8-948c-9b2fea96218e.png)

**Comment by davigun** [comment]
@duytq94 well, nice it works well. Thanks to you mate, your da best!!!
