### ISSUE TITLE
Gradle task assembleDebug failed error.

### ISSUE THREAD

**Issue by Sekaiichi4** [duytq94/flutter-chat-demo#22]
Hello Duy, first of all, thank you for sharing this project as it really helps me to learn more advanced Flutter development.

When I pulled the repository and opened the project, I, however, got the following error when trying to build the app on my Android phone with "Flutter run".

> Finished with error: Gradle task assembleDebug failed with exit code 1 

This error pops up on commit with index e2f0ef7.

The same error pops up if I open the project in Android Studio instead of Visual Studio Code.

Is there maybe something that I have missed or could this be a bug?

**Comment by duytq94** [comment]
Hi @Sekaiichi4 
I just update all plugins to the latest version and migrate to AndroidX.
So please go back the article again and come to **AndroidX compatibility issues** section I updated to solve the issue.

![Screen Shot 2019-07-10 at 10 29 20 PM](https://user-images.githubusercontent.com/24253421/60982372-32728800-a362-11e9-9e29-a88da0c73bc2.png)

**Comment by duytq94** [comment]
Btw, keep feeling free to discuss.
Thanks.
