### ISSUE TITLE
The app icon doesn't show in the notification panel

### ISSUE THREAD

**Issue by anapeksha** [duytq94/flutter-chat-demo#23]
Can't see the app icon in the notification panel! Basically shows a clear grey circle instead of the app_icon.png

**Comment by duytq94** [comment]
I tested this project and don't see anything wrong.
Btw, which platform, which device you got the issue?
A screenshot or more info will help easier to detect instead of just a simple report which can't find out anything.

**Comment by anapeksha** [comment]
I use android one!
And the screenshot is attached... the dot should have been the icon
![Screenshot_1563466115](https://user-images.githubusercontent.com/46746006/61473640-70942b00-a9a4-11e9-966d-2a5721e862b1.png)

**Comment by duytq94** [comment]
And you mean about the notification from flutter_local_notifications?
How about the notification from firebase_messaging?

**Comment by anapeksha** [comment]
Either of them doesn't work properly!

**Comment by duytq94** [comment]
Yes, I got the issue, some devices just show the grey square or circle.
Btw I just follow this https://github.com/flutter/flutter/issues/17941#issuecomment-412242466 but can't solve the problem.
So just keep searching, if you have any idea, please tell me.

**Comment by FilipeOS** [comment]
@anapeksha @duytq94 I don't use app_icon but @mipmap/ic_launcher :) so I don't need to generate a specific one, hope this helps

**Comment by anapeksha** [comment]
@FilipeOS this doesn't work either!

**Comment by FilipeOS** [comment]
Open a ticket on local notifications github. I think it might be a Android one issue
