### ISSUE TITLE
Issue with notifications

### ISSUE THREAD

**Issue by FilipeOS** [duytq94/flutter-chat-demo#27]
Hi @duytq94 

I have an issue and I need your help.

Notifications work nice BUT if you login with another user you will still get notified of that other user. 

For example you login with A and logout, if you send a message from B to A, you will get both. In my case I'm using the same notification to display add requests.

Can you advise please?

I tried this on logout but don't work:
```
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = new FlutterLocalNotificationsPlugin();
    await flutterLocalNotificationsPlugin.cancelAll();
```

**Comment by duytq94** [comment]
Hi, you should remove pushToken on Cloud Firestore before a user logout from their device. Because if you won't, 2 or more user account will have the same pushToken (~ same device).

**Comment by FilipeOS** [comment]
@duytq94 so on logout I delete the pushtoken of my logged in user?

**Comment by duytq94** [comment]
Yes, you should do this.
