### ISSUE TITLE
Open Image Bigger

### ISSUE THREAD

**Issue by wil340** [duytq94/flutter-chat-demo#28]
Hi, I'm trying to get the image in the chat box to be clickable and showed bigger on screen with the ability to zoom in/out. I've been trying to implement https://pub.dev/packages/photo_view without any success. 

I also found a way to connect GestureDetector to any images in the chatbox but I need external help to continue. 
//CODE
`   
 : document['type'] == 1
                  // Image

                  ? Container(
            child: GestureDetector(
              onTap: () {

              },
              child: Material(

                        child: CachedNetworkImage(
                          placeholder: (context, url) => Container(
                            child: CircularProgressIndicator(
                              valueColor: AlwaysStoppedAnimation<Color>(themeColor),
                            ),
                            width: 200.0,
                            height: 200.0,
                            padding: EdgeInsets.all(70.0),
                            decoration: BoxDecoration(
                              color: greyColor2,
                              borderRadius: BorderRadius.all(
                                Radius.circular(8.0),
                              ),
                            ),
                          ),

                          errorWidget: (context, url, error) => Material(
                            child: Image.asset(
                              'images/img_not_available.jpeg',
                              width: 200.0,
                              height: 200.0,
                              fit: BoxFit.cover,
                            ),
                            borderRadius: BorderRadius.all(
                              Radius.circular(8.0),
                            ),
                            clipBehavior: Clip.hardEdge,
                          ),

                          imageUrl: document['content'],
                          width: 200.0,
                          height:200.0,
                          fit: BoxFit.fill,
                        ),
                        borderRadius: BorderRadius.all(Radius.circular(8.0)),
                        clipBehavior: Clip.hardEdge,
                      ),

                    )
          ) `

  Thank you.

**Comment by duytq94** [comment]
Let's try photo_view, I tested and it works. I also add this feature to the code, please check out the latest commit.

![ezgif-4-e604d8bc0b39](https://user-images.githubusercontent.com/24253421/63222912-11f6e280-c1d8-11e9-971b-fff7542f7189.gif)

**Comment by wil340** [comment]
It work perfectly.
Thank you. I appreciate your work!
