### ISSUE TITLE
APP BREAK .. The behavior for java.util.Date objects stored in Firestore is going to change

### ISSUE THREAD

**Issue by RakhimyanTim** [duytq94/flutter-chat-demo#3]
Hi! Do You know how it solves? Plse help me to find the solution. Many thnks!

![image](https://user-images.githubusercontent.com/13000093/45589676-5f1c6580-b932-11e8-9d44-003f2684559d.png)

**Comment by davigun** [comment]
Can you run the app smoothly?

**Comment by RakhimyanTim** [comment]
> Can you run the app smoothly?

Hi @davigun What do you mean under 'smoothly'? Can you explain a little bit..

**Comment by davigun** [comment]
E/flutter ( 7521): [ERROR:flutter/shell/common/engine.cc(149)] Could not prepare to run the isolate.
E/flutter ( 7521): [ERROR:flutter/shell/common/engine.cc(114)] Engine not prepare and launch isolate.
E/flutter ( 7521): [ERROR:flutter/shell/platform/android/android_shell_holder.cc(136)] Could not launch engine in configuration.

i got this error message when running for the first time

**Comment by duytq94** [comment]
Hi @RakhimyanTim 
This is the warning when you use get date time in every item, but I don't use it in my project (I create my own timestamp field and use it instead of the default) so just ignore this warning.

**Comment by RakhimyanTim** [comment]
Thank you @duytq94  for your quick response. 

You know my  app breaek when I'm using release apk version of app. So I can not sign in (but evreything ok when it still state in developing status). I don't know actulally but it error might be related with [FireStore TimeStamp](https://github.com/flutter/plugins/pull/765)

Also I have another problem. 

When I'm trying to upload the images inside chat the app crashes. Pls find [code](https://github.com/Healthifykids/chat_app.github.io) below & tell me what am I doing wrong? Thanks!

**Comment by RakhimyanTim** [comment]
> E/flutter ( 7521): [ERROR:flutter/shell/common/engine.cc(149)] Could not prepare to run the isolate.
> E/flutter ( 7521): [ERROR:flutter/shell/common/engine.cc(114)] Engine not prepare and launch isolate.
> E/flutter ( 7521): [ERROR:flutter/shell/platform/android/android_shell_holder.cc(136)] Could not launch engine in configuration.
> 
> i got this error message when running for the first time @RakhimyanTim

Hi @davigun 
I found out this error also in first time but everything was resolved after adding run function.

**Comment by duytq94** [comment]
@RakhimyanTim can you give the log error, or it just happens at release, I haven't tested it with the release, do you sure about the keystore, google config file json?

**Comment by RakhimyanTim** [comment]
@duytq94 ooh I apologize. [Here](https://github.com/Healthifykids/chat_app.github.io) I've just updated it.

**Comment by RakhimyanTim** [comment]
@duytq94 Did you have a free time to check the app that I sent you above?

**Comment by duytq94** [comment]
Hi @RakhimyanTim 
You just post the **log error** to save the time.
Currently, I can't clone your code and setup to run.
Thanks!

**Comment by RakhimyanTim** [comment]
@duytq94 Currently I've no solution for [this](https://github.com/duytq94/flutter-chat-demo/issues/3#issue-360566688) error. I think it's not related with your [flutter-chat-demo](https://github.com/duytq94/flutter-chat-demo).
