### ISSUE TITLE
How to run the project with latest update?

### ISSUE THREAD

**Issue by wilson0506** [duytq94/flutter-chat-demo#30]
HI, I CANNOT EVEN BUILD THE PROJECT

**Comment by wilson0506** [comment]
I solved finally, everything now fine but only notification when message is not appear.

**Comment by ramadwiprasetia** [comment]
hi icannot open the project if i open the app the app will closed

**Comment by duytq94** [comment]
@ramadwiprasetia  I fresh cloned and the demo works fine. Please post your log here.
@wilson0506 I tested and notification on Android works fine, not sure if it working on iOS because my apple account is expired.

**Comment by ramadwiprasetia** [comment]
here
![3](https://user-images.githubusercontent.com/56752554/67647797-1b35c580-f966-11e9-9120-b55e7f0add8a.PNG)

**Comment by duytq94** [comment]
Your log is very clear that's your computer can not download the builder.jar.
Check your internet connection or you probably have Android Studio configured to use Gradle in offline mode
