### ISSUE TITLE
Load more messages on scroll

### ISSUE THREAD

**Issue by Nikualla1** [duytq94/flutter-chat-demo#36]
Hi, im new to flutter and was trying to change stream by loading more data on scroll top.
Since stream is listening to a firebase snapshots I couldn't find any way to modify it.
I know firebase can paginate by querying on the last document shown but I cannot update the changes on stream.
Is it possible?

**Comment by duytq94** [comment]
Load more was implemented in this https://github.com/duytq94/flutter-chat-demo/pull/43/commits/27bf2321864cf7a438ffa915d2b853acf3eeaf03 commit and has been merge to master, please checkout the latest code.
