### ISSUE TITLE
Google login issue

### ISSUE THREAD

**Issue by fgrenoville** [duytq94/flutter-chat-demo#38]
Google login doesn't work.
I got following error:

`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)`

and stuck on loading screen.

**Comment by duytran4** [comment]
I just test it and nothing wrong happen. Can you describe more detail about your steps and maybe you should test on your real device.

**Comment by duytq94** [comment]
I just test it and nothing wrong happen. Can you describe more detail about your steps and maybe you should test on your real device.
