### ISSUE TITLE
Login with google hangs

### ISSUE THREAD

**Issue by mariakhala** [duytq94/flutter-chat-demo#40]
Hi when i use my googleservices.json file it hangs on google sign in how ever it works with yours and in my new json file only invite services are present while in yours analytics are present however i added with gradle but still unable to login it keeps on loading

**Comment by duytq94** [comment]
Hi, you should re-check your googleservices.json configure since I don't know what you did, maybe https://pub.dev/packages/google_sign_in can help you.

**Comment by mohamedlouati** [comment]
thank you
