### ISSUE TITLE
Chat with flutter BLoC ?

### ISSUE THREAD

**Issue by veyhong** [duytq94/flutter-chat-demo#41]
Thank you for sharing amazing work for chat on flutter. 
Just suggestion, is there anyway you can giving sample on implement is same flutter chat with [flutter_bloc]( https://pub.dev/packages/flutter_bloc) ?  since it is a very popular. :)

**Comment by duytq94** [comment]
Hi, I haven't had time at the moment to implement this, a pull request is very appreciate.

**Comment by mohamedlouati** [comment]
thank you
