### ISSUE TITLE
Showing off latest chat in main screen

### ISSUE THREAD

**Issue by harshapulikollu** [duytq94/flutter-chat-demo#5]
Hi sir, I liked your work and the messaging is working fine and I'm able to use it. But I have to know how to implement to show latest messages from users in main page(like all chat apps do) instead of showing just all users. If I send new message then peer user should see the latest message I send to user along with  their display pic and rest messages should go a step down. I tried so much to do it by myself but I have user details like name display pic and etc. in other collections and messages in other collection. I'm unable to combine these two data and show users latest message from others with their pics and latest message.
Please help me out of this....

**Comment by Abosrie** [comment]
You have to use Future Builder along with the stream builder.
Call a new function from the future builder to fetch all the user from the user collection. then loop on the message collection by the peerId and current user Id to get the last msg.

**Comment by duytq94** [comment]
Hi @harshapulikollu 
When sending a message, you can **push** the content message into 2 nodes (the 1st node is group node - like the current code does, the 2nd node is a user node (both in current user and peer user), you should add a collection name `latestMessage`, and this collection have a list latest messages for each user.
After that, when you load the list users, in each user, you load it's collection and find the current user ID, that is the latest message between current user and that user.
![capture](https://user-images.githubusercontent.com/24253421/48297402-91cd7f00-e4d9-11e8-876b-1756adb7ff0e.PNG)

**Comment by harshapulikollu** [comment]
Okay thank you for your explanation and I'll try and it out.
