### ISSUE TITLE
firebase storage issues

### ISSUE THREAD

**Issue by AtulSisodiya** [duytq94/flutter-chat-demo#50]
![Screenshot 2021-02-06 145647](https://user-images.githubusercontent.com/56028094/107114358-3d1d3800-688b-11eb-832a-993140c82dad.jpg)

error related to firebase storage

**Comment by huzzi** [comment]
Change the 4 lines to 

`  
Reference reference = FirebaseStorage.instance.ref().child(fileName);

    UploadTask uploadTask = reference.putFile(image);

    TaskSnapshot storageTaskSnapshot = await uploadTask;

    imageUrl = await storageTaskSnapshot.ref.getDownloadURL();`

**Comment by duytq94** [comment]
Maybe you changed version firebase so the syntax changed too, read the firebase docs to update these code or get the same version as my demo
<img width="281" alt="Screen Shot 2021-02-17 at 3 28 05 PM" src="https://user-images.githubusercontent.com/24253421/108176533-bc84f400-7134-11eb-9fd2-447c0d5d00c9.png">
