### ISSUE TITLE
Question: (Design related) Recommended way of Firebase[Firestore][Auth] instance state management.

### ISSUE THREAD

**Issue by KartikShrivastava** [duytq94/flutter-chat-demo#54]
Hi,
Thanks for putting up this great project.
I'm a bit new to flutter(mobile app development) and seeing your project a bit surprised that you're not using any external package for state management. Like I've seen most people are using provider or redux or BLOC to decouple network logic from UI. And in this project most Firebase functionality is coupled with UI.
So, for a project which is supposed to scale what is the recommended way? Is the design which you've chosen is good for large scale apps too? Or are there any caveats?

**Comment by Baksman** [comment]
provider is cool,provided u use a better architecture,like mvvm

**Comment by duytq94** [comment]
Hi,
Thanks for your good advice.
This project was made from the state management library not popular as it is now, so I just maintain the main feature code without any change architecture.
Will do it in the feature when I have more time.
If you can help with a PR, very appreciate.

**Comment by KartikShrivastava** [comment]
So far I've leart most chat functionality with your repo and abstracted it with provider and recent cloud-functions[messaging] packages. Although I won't promise as I'm actively involved in another project but will try my best in near future to pull those additions here.

**Comment by duytq94** [comment]
Hi all, I just apply provider to this project, please check https://github.com/duytq94/flutter-chat-demo/pull/55
Thanks.

**Comment by KartikShrivastava** [comment]
Thanks for the update, appreciate that.

**Comment by adarsh927** [comment]
https://github.com/adarsh927/Library-Management-System


Please check my Project. I am in class 12 and done this as a part of my project. So please help me make it more perfect.

**Comment by adarsh927** [comment]
> https://github.com/adarsh927/Library-Management-System
> 
> 
> Please check my Project. I am in class 12 and done this as a part of my project. So please help me make it more perfect. 

It's a python and MySQL integrated project.
