### ISSUE TITLE
Getting the old msg!

### ISSUE THREAD

**Issue by Abosrie** [duytq94/flutter-chat-demo#6]
Hey, 
Thanks for the project; I'm using it while learning Flutter SDK.
I have a question - How can we get the older msgs as the fetched msgs is limited to 20 only.

**Comment by duytq94** [comment]
Thanks for your questions.
Close since we discussed it at here: https://medium.com/@ahmedaabosrie/thanks-a-lot-and-good-job-4fdc8b37e279
