### ISSUE TITLE
What is the version of flutter?

### ISSUE THREAD

**Issue by hua-qian-yue-xia** [duytq94/flutter-chat-demo#72]

**Comment by duytq94** [comment]
Hi, the last time a run project with
> Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (4 months ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2
and it works.
Did you have an issue with the newer Flutter version?

**Comment by duytq94** [comment]
Hi, the last time a run project with
> Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (4 months ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

and it works.
Did you have an issue with the newer Flutter version?
