### ISSUE TITLE
Message delivery report/status

### ISSUE THREAD

**Issue by harshapulikollu** [duytq94/flutter-chat-demo#8]
Hi, I want to know the best possible way to implement message delivery report (like **delivered, seen**) which will be shown to sender for every message.  
Please provide me an idea what I have to do in firestore and in client (user) side.

**Comment by duytq94** [comment]
Hi @harshapulikollu 
I think you should add more field in every message, like if peer user received your message, they should update this attribute in that message, and then you'll get that message again and check attribute to update the status message.

**Comment by harshapulikollu** [comment]
Thanks for your reply sir, 
How can I know whether user received that particular message in device!! That's my actual doubt.

**Comment by harshapulikollu** [comment]
Got it, I'll try it. Thanks for your help.
