### ISSUE TITLE
error in sign

### ISSUE THREAD

**Issue by mishubham** [duytq94/flutter-chat-demo#9]
D/Surface ( 6720): Surface::disconnect(this=0x713117a000,api=1)
E/flutter ( 6720): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 6720): PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 12500: , null)
D/WindowClient( 6720): Remove from mViews: DecorView@5e372b2[SignInHubActivity], this = android.view.WindowManagerGlobal@c0f268f

console messages

**Comment by poshl000** [comment]
Have same issue

**Comment by duytq94** [comment]
I just clone and run the project from scratch, everything still fine.
Did you use the AVD instead of the real device, this issue is related to Google Play Services. Maybe you need to update Google Play Services to the latest version.

**Comment by AxesandGrinds** [comment]
I fixed this error by simply switching to use facebook firebase login. Google was proving to be too problematic. @duytq94, you didn't provide any steps for setting up the keystore or making sure that google firebase login works if attempted from scratch, you didn't provide any information for that in your read me or web article.
